# Dictionary

In [1]:
# DICTIONARY
# u can use any name in the place of "dic"
dic={}              #Initializing dictionary
print(type(dic))          

dic={                        #creating dictionary
    'Name':'Roopneet',
    'Qualification':'10th',
    'age':15,
}

print(dic)                 #Accessing elements from the dictionary
print(dic['Name'])
print(dic.get('age'))

dic['Phone number']='9876543213'         #Inserting values
print(dic)

dic['Phone number']='1234567899'          #Updating values
print(dic)
del dic                    #Deleting dictionary
print(dic)

<class 'dict'>
{'Name': 'Roopneet', 'Qualification': '10th', 'age': 15}
Roopneet
15
{'Name': 'Roopneet', 'Qualification': '10th', 'age': 15, 'Phone number': '9876543213'}
{'Name': 'Roopneet', 'Qualification': '10th', 'age': 15, 'Phone number': '1234567899'}


NameError: name 'dic' is not defined

In [10]:
data= [['Name','Roopneet'],['Qualification','10th'],['Age',15]]
print(type(data))
print(data)
print(data[0][1])
print(data[2][1])

add=[['Phone number','9876543211']]
data_new= data+add
print(data_new)

data.append(['Phone number','9876543211'])
print(data)

data_new[3][1]='1234567899'
print(data_new)

del data

<class 'list'>
[['Name', 'Roopneet'], ['Qualification', '10th'], ['Age', 15]]
Roopneet
15
[['Name', 'Roopneet'], ['Qualification', '10th'], ['Age', 15], ['Phone number', '9876543211']]
[['Name', 'Roopneet'], ['Qualification', '10th'], ['Age', 15], ['Phone number', '9876543211']]
[['Name', 'Roopneet'], ['Qualification', '10th'], ['Age', 15], ['Phone number', '1234567899']]


In [3]:
#Updating numpy arrays
import numpy as np
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
A[2,1]=150
print(A)

[[  1   2   3   4]
 [  5   6   7   8]
 [  9 150  11  12]
 [ 13  14  15  16]]


In [4]:
import numpy as np
data= np.array([['Name','Roopneet'],['Qualification','10th'],['Age',15],['Phone number','9876543211']])
print(type(data))
print(data)
print(data[0][1])
print(data[2][1])

data[3,1]=1234567899
print(data)
# array cant be updated after append function has been used.
a=[['Phone number','9876543211']]
data= np.append(data,a)
print(data)

<class 'numpy.ndarray'>
[['Name' 'Roopneet']
 ['Qualification' '10th']
 ['Age' '15']
 ['Phone number' '9876543211']]
Roopneet
15
[['Name' 'Roopneet']
 ['Qualification' '10th']
 ['Age' '15']
 ['Phone number' '1234567899']]
['Name' 'Roopneet' 'Qualification' '10th' 'Age' '15' 'Phone number'
 '1234567899' 'Phone number' '9876543211']


In [5]:
# Revision of old topic..
a=(int(input("Enter a number ,that you want to check ")))
if a % 2 ==0 :
    print("The given number is even ")
else :
    print("The given number is odd ")

Enter a number ,that you want to check 24
The given number is even 


In [6]:
y = int(input("Enter the year ,that you want to check "))
if (a % 4) ==0 :
    print("{0} It is a leap year".format(a))
else :
    print( "It is not a leap year ")
    # it is not working without using format

Enter the year ,that you want to check 2012
24 It is a leap year


In [7]:
 a= int(input("Enter the year you want to check "))
if (a % 4) ==0:
      print("{0} is a leap year".format(a))
else:
     print("It is not a leap year")

Enter the year you want to check 2023
It is not a leap year


In [8]:
#Write code to find the greatest of three numbers

a = int(input("Enter a number a "))
b = int(input("Enter a number b "))
c = int(input("Enter a number c "))
if (a>b) and (a>c):
    print("a is greatest ")
elif (b>c) and (b>a):
    print("b is greatest ")
else  :
    print("c is greatest ")


Enter a number a 2
Enter a number b 4
Enter a number c 67
c is greatest 


In [9]:
mean={}
mean= {
    'Beseech':'to ask or enter',
    'Crumple':'to crush',
    'Excel':'to go beyond',
    'Frost':'frozen dew ',
    'Gripe':'to hold fast',
    'Horrid':'dreadful',
    'Lavish':'extravagant',
    'Owe':'to be under obligation',
    'Psyche':'soul,mind',
    'Traduce':'to misrepresent',
}
print(mean)
mean['Rely']='on to have trust in'
print(mean)
mean['Rely']='to depend on someone or something'
print(mean)
del(mean['Rely'])
print(mean)

{'Beseech': 'to ask or enter', 'Crumple': 'to crush', 'Excel': 'to go beyond', 'Frost': 'frozen dew ', 'Gripe': 'to hold fast', 'Horrid': 'dreadful', 'Lavish': 'extravagant', 'Owe': 'to be under obligation', 'Psyche': 'soul,mind', 'Traduce': 'to misrepresent'}
{'Beseech': 'to ask or enter', 'Crumple': 'to crush', 'Excel': 'to go beyond', 'Frost': 'frozen dew ', 'Gripe': 'to hold fast', 'Horrid': 'dreadful', 'Lavish': 'extravagant', 'Owe': 'to be under obligation', 'Psyche': 'soul,mind', 'Traduce': 'to misrepresent', 'Rely': 'on to have trust in'}
{'Beseech': 'to ask or enter', 'Crumple': 'to crush', 'Excel': 'to go beyond', 'Frost': 'frozen dew ', 'Gripe': 'to hold fast', 'Horrid': 'dreadful', 'Lavish': 'extravagant', 'Owe': 'to be under obligation', 'Psyche': 'soul,mind', 'Traduce': 'to misrepresent', 'Rely': 'to depend on someone or something'}
{'Beseech': 'to ask or enter', 'Crumple': 'to crush', 'Excel': 'to go beyond', 'Frost': 'frozen dew ', 'Gripe': 'to hold fast', 'Horrid': 'dr